const axios = require('axios');
const { getTeamElo } = require('./featureEngineering');

const HOME_ADVANTAGE = 70;
const MODEL_TIMEOUT = 3000;

function eloToExpected(eloDiff) {
  return 1 / (1 + Math.pow(10, -eloDiff / 400));
}

function determineConfidence(prob) {
  if (prob > 70) return 'High';
  if (prob > 55) return 'Medium';
  return 'Low';
}

function eloFallbackPrediction(homeElo, awayElo) {
  const eloDiff = homeElo - awayElo + HOME_ADVANTAGE;
  const expected = eloToExpected(eloDiff);

  const drawBase = 0.26;
  const drawFactor = 1 - Math.abs(expected - 0.5);
  const drawProb = Math.round(drawBase * drawFactor * 100);

  const remaining = 100 - drawProb;
  let homeProb = Math.round(remaining * expected);
  let awayProb = remaining - homeProb;

  const diff = homeProb + awayProb + drawProb - 100;
  if (diff !== 0) {
    const maxIdx = homeProb >= awayProb && homeProb >= drawProb ? 'home'
                 : awayProb >= homeProb && awayProb >= drawProb ? 'away'
                 : 'draw';
    if (maxIdx === 'home') homeProb -= diff;
    else if (maxIdx === 'away') awayProb -= diff;
    else drawProb -= diff;
  }

  const highestProb = Math.max(homeProb, awayProb, drawProb);
  let predictedOutcome;
  if (homeProb === highestProb) predictedOutcome = 'H';
  else if (awayProb === highestProb) predictedOutcome = 'A';
  else predictedOutcome = 'D';

  const factors = [
    `Home team Elo rating is ${Math.abs(homeElo - awayElo)} points ${homeElo > awayElo ? 'higher' : 'lower'} than away team`,
    `Home advantage contributes approximately ${Math.round((HOME_ADVANTAGE / (Math.abs(eloDiff) + HOME_ADVANTAGE)) * 100)}% boost to home expectancy`,
    `Expected home win probability of ${homeProb}% based on Elo model`
  ];

  return {
    success: true,
    predictedOutcome,
    probabilities: { home: homeProb, draw: drawProb, away: awayProb },
    confidence: determineConfidence(highestProb),
    keyFactors: factors
  };
}

async function getPrediction(homeTeam, awayTeam, featureVector) {
  try {
    const response = await axios.post(
      process.env.MODEL_SERVICE_URL + '/predict',
      { features: featureVector },
      { timeout: MODEL_TIMEOUT }
    );

    if (response.data && response.data.predictedOutcome) {
      return {
        success: true,
        predictedOutcome: response.data.predictedOutcome,
        probabilities: response.data.probabilities,
        confidence: response.data.confidence || 'Medium',
        keyFactors: response.data.keyFactors || ['Prediction generated by XGBoost model']
      };
    }
    throw new Error('Invalid response from model service');
  } catch (err) {
    console.warn('Model service unavailable, using Elo fallback:', err.message);
    const homeElo = await getTeamElo(homeTeam);
    const awayElo = await getTeamElo(awayTeam);
    return eloFallbackPrediction(homeElo, awayElo);
  }
}

module.exports = { getPrediction, eloFallbackPrediction };
