"""Train an XGBoost match-outcome classifier from exported training data.

Reads backend/data/training.jsonl (generated by exportTrainingData.js),
trains a 3-class model (H/D/A), evaluates on a chronological holdout
(last season), and saves model.json + model_meta.json into model-service/model/.

Usage: python train_model.py
"""

import json
import os
from datetime import date

import numpy as np
import xgboost as xgb

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(HERE, "..", "backend", "data", "training.jsonl")
DATA_META_PATH = os.path.join(HERE, "..", "backend", "data", "training_meta.json")
OUT_DIR = os.path.join(HERE, "model")
OUT_MODEL = os.path.join(OUT_DIR, "model.json")
OUT_META = os.path.join(OUT_DIR, "model_meta.json")

CLASSES = ["H", "D", "A"]
CLASS_IDX = {c: i for i, c in enumerate(CLASSES)}

# Chronological holdout: train on all seasons before this date, test on the rest
HOLDOUT_START = "2025-08-01"


def main():
    if not os.path.isfile(DATA_PATH):
        raise SystemExit(f"Training data not found: {DATA_PATH}\nRun: npm run export-data")

    rows = []
    with open(DATA_PATH, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))

    print(f"Loaded {len(rows)} samples")
    if not rows:
        raise SystemExit("No training samples")

    # Feature names from the exporter (training_meta.json)
    feature_names = []
    if os.path.isfile(DATA_META_PATH):
        with open(DATA_META_PATH, "r", encoding="utf-8") as f:
            feature_names = json.load(f).get("feature_names", [])

    n_features = len(rows[0]["features"])
    print(f"Feature count: {n_features}")
    if feature_names:
        print(f"Feature names: {', '.join(feature_names)}")

    X = np.array([r["features"] for r in rows], dtype=np.float32)
    y = np.array([CLASS_IDX[r["label"]] for r in rows], dtype=np.int32)
    dates = np.array([r["date"] for r in rows])

    train_mask = dates < HOLDOUT_START
    test_mask = ~train_mask
    print(f"Train: {train_mask.sum()} samples (before {HOLDOUT_START}), "
          f"Test: {test_mask.sum()} samples")

    dtrain = xgb.DMatrix(X[train_mask], label=y[train_mask])
    dtest = xgb.DMatrix(X[test_mask], label=y[test_mask])

    params = {
        "objective": "multi:softprob",
        "num_class": 3,
        "max_depth": 6,
        "eta": 0.1,
        "subsample": 0.9,
        "colsample_bytree": 0.9,
        "min_child_weight": 5,
        "eval_metric": "mlogloss",
        "seed": 42,
    }

    bst = xgb.train(params, dtrain, num_boost_round=200, evals=[(dtest, "test")],
                    early_stopping_rounds=20, verbose_eval=False)
    best_iter = bst.best_iteration if bst.best_iteration is not None else 200
    print(f"Best iteration: {best_iter}")

    pred_probs = bst.predict(dtest)
    pred_class = np.argmax(pred_probs, axis=1)
    y_test = y[test_mask]

    # Metrics: accuracy + macro precision/recall/F1
    correct = (pred_class == y_test).sum()
    accuracy = correct / len(y_test)

    precisions, recalls = [], []
    for c in range(3):
        tp = ((pred_class == c) & (y_test == c)).sum()
        fp = ((pred_class == c) & (y_test != c)).sum()
        fn = ((pred_class != c) & (y_test == c)).sum()
        precisions.append(tp / (tp + fp) if tp + fp else 0)
        recalls.append(tp / (tp + fn) if tp + fn else 0)
    precision = np.mean(precisions)
    recall = np.mean(recalls)
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0

    print(f"\n=== Holdout results ({len(y_test)} matches) ===")
    print(f"Accuracy : {accuracy*100:.2f}%")
    print(f"Precision: {precision*100:.2f}%")
    print(f"Recall   : {recall*100:.2f}%")
    print(f"F1       : {f1*100:.2f}%")
    for c, name in enumerate(CLASSES):
        share = (y_test == c).mean()
        print(f"  {name}: {share*100:.1f}% of holdout")

    os.makedirs(OUT_DIR, exist_ok=True)
    bst.save_model(OUT_MODEL)

    with open(OUT_META, "w", encoding="utf-8") as f:
        json.dump({
            "classes": CLASSES,
            "feature_names": feature_names,
            "n_features": n_features,
            "metrics": {
                "accuracy": round(accuracy * 100, 2),
                "precision": round(precision * 100, 2),
                "recall": round(recall * 100, 2),
                "f1": round(f1 * 100, 2),
            },
            "trained_at": date.today().isoformat(),
            "holdout_start": HOLDOUT_START,
            "train_samples": int(train_mask.sum()),
            "test_samples": int(test_mask.sum()),
            "best_iteration": best_iter,
        }, f, indent=2)

    print(f"\nSaved model: {OUT_MODEL}")
    print(f"Saved meta : {OUT_META}")


if __name__ == "__main__":
    main()
