import json
import logging
import os

import numpy as np
import xgboost as xgb
from flask import Flask, jsonify, request
from flask_cors import CORS

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)
CORS(app)

HERE = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(HERE, "..", "model", "model.json")
META_PATH = os.path.join(HERE, "..", "model", "model_meta.json")

CLASSES = ["H", "D", "A"]
CONFIDENCE_NAMES = {0: "Low", 1: "Medium", 2: "High"}
CONFIDENCE_THRESHOLDS = [55, 70]  # max prob thresholds for Low/Medium/High

bst = None
meta = {}


def load_model():
    global bst, meta
    if not os.path.isfile(MODEL_PATH):
        logger.warning("Model file not found at %s", MODEL_PATH)
        return
    bst = xgb.Booster()
    bst.load_model(MODEL_PATH)
    if os.path.isfile(META_PATH):
        with open(META_PATH, "r", encoding="utf-8") as f:
            meta = json.load(f)
    logger.info("Loaded XGBoost model (features=%s, trained=%s)",
                meta.get("n_features", "?"), meta.get("trained_at", "?"))


load_model()


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "service": "footpredict-model",
                    "model_loaded": bst is not None,
                    "model_version": meta.get("trained_at", "none")})


def _confidence(max_prob):
    if max_prob >= CONFIDENCE_THRESHOLDS[1]:
        return "High"
    if max_prob >= CONFIDENCE_THRESHOLDS[0]:
        return "Medium"
    return "Low"


def _key_factors(probs, feature_names, features):
    """Human-readable rationale using the most influential features."""
    if not feature_names or len(feature_names) != len(features):
        return ["Prediction generated by XGBoost model"]
    fmap = dict(zip(feature_names, features))
    factors = []
    elo_diff = fmap.get("elo_diff", 0)
    if abs(elo_diff) >= 50:
        factors.append(
            f"Elo rating gap of {abs(elo_diff):.0f} points "
            f"({'favoring the home side' if elo_diff > 0 else 'favoring the away side'})")
    rest_diff = fmap.get("home_rest_days", 0) - fmap.get("away_rest_days", 0)
    if abs(rest_diff) >= 3:
        factors.append(
            f"Rest advantage of {abs(rest_diff):.0f} days "
            f"({'for the home team' if rest_diff > 0 else 'for the away team'})")
    if fmap.get("derby_flag", 0) == 1:
        factors.append("Local derby — form often takes a back seat")
    if fmap.get("h2h_matches", 0) >= 4:
        factors.append(
            f"{fmap.get('h2h_matches', 0):.0f} head-to-head meetings in the last 3 seasons "
            f"considered (home win ratio {fmap.get('h2h_home_win_ratio', 0):.0%})")
    if not factors:
        factors.append("Balanced model inputs across Elo, form, H2H and rest")
    return factors


@app.route("/predict", methods=["POST"])
def predict():
    if bst is None:
        return jsonify({"success": False, "message": "Model not loaded"}), 503

    body = request.get_json(silent=True) or {}
    features = body.get("features", [])
    if not features:
        return jsonify({"success": False, "message": "No features provided"}), 400

    try:
        dmatrix = xgb.DMatrix(np.array([features], dtype=np.float32))
        probs = bst.predict(dmatrix)[0]
    except Exception as e:
        logger.exception("Prediction failed")
        return jsonify({"success": False, "message": f"Prediction failed: {e}"}), 500

    probs_pct = (probs * 100).round().astype(int)
    pred_idx = int(np.argmax(probs_pct))

    # Normalize so probabilities sum to exactly 100
    diff = int(probs_pct.sum()) - 100
    if diff != 0:
        probs_pct[pred_idx] -= diff

    return jsonify({
        "success": True,
        "predictedOutcome": CLASSES[pred_idx],
        "probabilities": {
            "home": int(probs_pct[0]),
            "draw": int(probs_pct[1]),
            "away": int(probs_pct[2])
        },
        "confidence": _confidence(int(probs_pct[pred_idx])),
        "keyFactors": _key_factors(probs_pct, meta.get("feature_names", []), features),
        "modelVersion": meta.get("trained_at", "unknown")
    })


if __name__ == "__main__":
    port_env = os.environ.get("PORT", "")
    if not port_env:
        env_path = os.path.join(HERE, "..", ".env")
        if os.path.isfile(env_path):
            with open(env_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if line.startswith("PORT="):
                        port_env = line.split("=", 1)[1].strip().strip("'\"")
                        break
    port = int(port_env) if port_env else 5001
    app.run(host="0.0.0.0", port=port, debug=True)
